### ISSUE TITLE
'multiprocess' not found in requirements.txt

### ISSUE THREAD

**Issue by vwieczorek** [chrismaddalena/ODIN#13]
The included requirements.txt does not include 'multiprocess' and thus needs to be installed separately on Mac 10.12.6.

**Comment by chrismaddalena** [comment]
Thanks for the heads up! This has been fixed in the latest push. I did add it to the requirements.txt file. However, I have now deprecated that file. It remains in the setup directory, but I now recommend using the Pipfile with pipenv.
