### ISSUE TITLE
URLCrazy path hardcoded in domain_tools.py

### ISSUE THREAD

**Issue by julianrutz** [chrismaddalena/ODIN#15]
The path to urlcrazy seems to be handcoded in domain_tools.py:

$ cat lib/domain_tools.py | grep cmaddy
            subprocess.call("/Users/cmaddy/Lab/URLCrazy/urlcrazy")
                cmd = "/Users/cmaddy/Lab/URLCrazy/urlcrazy -f csv -o '{}' {}".format(outfile, target)

**Comment by chrismaddalena** [comment]
Ha, you're right! I put that in for testing and it slipped my mind. Thanks for pointing it out. I'll fix it now.
