### ISSUE TITLE
Boto Exception Not Caught

### ISSUE THREAD

**Issue by radioboyQ** [chrismaddalena/ODIN#16]
When credentials for AWS are not provided, ODIN shows a traceback.

`[+] Running urlcrazy for REDACTED
Process Cloud Report:
Traceback (most recent call last):  

 <--SNIP-->

botocore.exceptions.NoCredentialsError: Unable to locate credentials`

**Comment by chrismaddalena** [comment]
Thanks for letting me know. This has been fixed and I will push the code shortly.
