### ISSUE TITLE
Domains containing hyphens interpreted as IP range

### ISSUE THREAD

**Issue by 0xhexmex** [chrismaddalena/ODIN#19]
It seems like when parsing the scope file passed with -sf, ODIN interprets a domain containing a hyphen as an IP range.

```
[+] blah123-online.com is a range - expanding...
[!] Parsing of scope file failed!
L.. Details: list index out of range
```

**Comment by chrismaddalena** [comment]
Thanks for the report! This was a super easy fix. It was resolved with the latest update.

https://github.com/chrismaddalena/ODIN/commit/7a4c8bfcb8c1457e454a07b243c5573f97c41b1f
