### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by CrazianT3k** [chrismaddalena/ODIN#24]
Aloha,

I got the following error while running ODIN:

Release v1.9.2, MUNINN
[+] OSINT Module Selected: ODIN will run all recon modules.
[*] Headless Chrome browser test was successful!
[+] Beginning initial discovery phase! This could take some time...
[+] Starting new process: Company Info Collector
[+] Starting new process: Employee Hunter
[+] Starting new process: Domain and IP Address Recon
[+] Beginning the harvesting of email addresses for redacted.com...
[*] Harvesting Google
Process Domain and IP Address Recon:
Traceback (most recent call last):
  File "/Users/XXXXXXXXX/.virtualenvs/ODIN-4yBUt_eV/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/XXXXXXXXX/.virtualenvs/ODIN-4yBUt_eV/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/tools/ODIN/lib/reporter.py", line 316, in create_domain_report_table
    if not any(x.strip(",").strip().lower() in whois_privacy for x in org_name.split(" ")):
AttributeError: 'NoneType' object has no attribute 'split'

After some googling, I found the following link that could possibly fix this issue:
[https://gis.stackexchange.com/questions/185135/attributeerror-nonetype-object-has-no-attribute-split-from-arcmap-only](url)

So this could be another python 3.7 compatibility issue or the script needs to check for a NULL attribute before splitting.

Cheers!

**Comment by chrismaddalena** [comment]
Thanks for reporting this! The issue stemmed from a potential situation where a whois lookup would return no organization and the database would contain a NULL value. That NULL/None would be added as a list item when enumerating organizations and cause issues. ODIN now skips adding the organization to the list if the whois record's organization is NULL.

Fixed and included in the next commit.
