### ISSUE TITLE
colors module import issue

### ISSUE THREAD

**Issue by cottons1618** [chrismaddalena/ODIN#25]
I tried running the setup function and received an import error. Apparently I can't seem to find the colors package.  

`Traceback (most recent call last):`
  `File "setup_check.py", line 8, in <module>`
    `from colors import red, green, yellow`
`ImportError: cannot import name 'red' from 'colors'`

I've tried tracking it down and installing with pip to no avail. I'm new to python and this is one of my first projects in it so I apologize if this is a silly error.

**Comment by chrismaddalena** [comment]
Yea, this module seems to cause issues for some people. It's in the Pipfile, but it seems to not install properly for some. The module is `ansicolors`.

I recommend using the dev branch. I've removed the `ansicolors` module from that entirely to avoid the issue and make things simpler.

**Comment by cottons1618** [comment]
Hey thanks for the quick response, that appears to have fixed it. I'm having a couple other issues I'm now having. 

When I run the setup_check.py I get the following:
`?[31m[!] Provide your keys.config for review?[0m`
`?[31mL.. Usage: setup_check.py auth/keys.config?[0m`

I think its looking for the config file somewhere else or its expecting it to be named something else. Any possible solutions? Again, I definitely appreciate the support.

**Comment by chrismaddalena** [comment]
You need to provide the path to your keys.config file o the command line, like so:

`setup_check.py auth/keys.config`

**Comment by cottons1618** [comment]
Awesome, that did it! Thanks!
