### ISSUE TITLE
Metadata issues while downloading multiprocessor

### ISSUE THREAD

**Issue by n1t3m0dular** [chrismaddalena/ODIN#33]
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
pip3 install multiprocessing
Defaulting to user installation because normal site-packages is not writeable
Collecting multiprocessing
  Downloading multiprocessing-2.6.2.1.tar.gz (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.0/108.0 kB 131.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-v5w213gd/multiprocessing_6569445ef88848fc8a94f123a8ab9cf8/setup.py", line 94
          print 'Macros:'
          ^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by chrismaddalena** [comment]
Hey there, this is an issue related to Python's `setuptools`. If you search for the error you can find quite a few StackExchange conversations from this year on the topic. The solution may depend on your OS and the version of `setuptools` you have installed.

This thread had some good suggestions: https://stackoverflow.com/questions/70916814/error-metadata-generation-failed-cant-install-artic-module

I expect you will need to upgrade `setuptools` with `pip install --upgrade setuptools`.
