### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by radioboyQ** [chrismaddalena/ODIN#6]
`SyntaxError: keyword can't be an expression`
Checked to ensure that I had all of the requirements installed by running the master branch, it worked fine. 

https://github.com/chrismaddalena/viper/blob/5c3c0c916c25f3b2f929f8eafbabc67336d05a86/lib/domain_tools.py#L686

**Comment by chrismaddalena** [comment]
Thanks for reporting it! This is fixed. I just need to push the code. I will do so shortly.
